-- Safe columns for billing/settings (idempotent)
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "plan" TEXT NOT NULL DEFAULT 'FREE';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "creditsBalance" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "monthlyCredits" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "autoTopUp" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "autoTopUpThreshold" INTEGER NOT NULL DEFAULT 2000;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "autoTopUpAmount" INTEGER NOT NULL DEFAULT 10000;
