import { generateBlueprint } from "./blueprint";

type Blueprint = {
  name?: string;
  description?: string;
  features?: string[];
  pages?: string[];
  apiEndpoints?: string[];
  databaseModels?: string[];
  modules?: string[];
};

function safeSlug(input: string) {
  return (
    input
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "") || "iblacker-app"
  );
}

function normalizePagePath(p: string) {
  return p
    .trim()
    .replace(/^\/+/, "")
    .replace(/\/+$/, "")
    .replace(/\s+/g, "-");
}

function normalizeApiPath(p: string) {
  return p
    .trim()
    .replace(/^\/+/, "")
    .replace(/\/+$/, "")
    .replace(/\s+/g, "-");
}

function pageTemplate(title: string, description: string) {
  return `export default function Page() {
  return (
    <main style={{ padding: 40, fontFamily: "system-ui" }}>
      <h1 style={{ fontSize: 28, fontWeight: 800, marginBottom: 12 }}>${title}</h1>
      <p style={{ opacity: 0.75 }}>${description}</p>
    </main>
  );
}
`;
}

function apiTemplate(name: string) {
  return `import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    ok: true,
    endpoint: "${name}",
    message: "Stub endpoint generated by IBlacker. Implement logic here."
  });
}

export async function POST(req: Request) {
  const body = await req.json().catch(() => null);
  return NextResponse.json({
    ok: true,
    endpoint: "${name}",
    received: body
  });
}
`;
}

/** ===== Step 18.6.1 helpers ===== */
function has(modules: string[], name: string) {
  return modules.includes(name);
}

function envExample(modules: string[]) {
  const lines: string[] = [];
  lines.push(`# Generated by IBlacker`);
  lines.push(``);

  if (has(modules, "auth")) {
    lines.push(`NEXTAUTH_URL=http://localhost:3000`);
    lines.push(`NEXTAUTH_SECRET=change_me_to_a_long_random_secret`);
    lines.push(`GOOGLE_CLIENT_ID=`);
    lines.push(`GOOGLE_CLIENT_SECRET=`);
    lines.push(``);
  }

  if (has(modules, "db")) {
    lines.push(`DATABASE_URL=postgresql://USER:PASSWORD@HOST:5432/DB?schema=public`);
    lines.push(``);
  }

  if (has(modules, "payments")) {
    lines.push(`STRIPE_SECRET_KEY=`);
    lines.push(`STRIPE_WEBHOOK_SECRET=`);
    lines.push(`NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=`);
    lines.push(``);
  }

  return lines.join("\n");
}

/** ===== Main generator ===== */
export async function generateProjectFiles(
  prompt: string,
  modules: string[] = []
) {
  const blueprint = (await generateBlueprint(prompt, modules)) as Blueprint;

  const safeName = safeSlug(blueprint.name || "iblacker-app");

  /** ===== Step 18.6.2 module deps ===== */
  const deps: Record<string, string> = {
    next: "^15.0.0",
    react: "^18.0.0",
    "react-dom": "^18.0.0",
  };

  const devDeps: Record<string, string> = {
    typescript: "^5.0.0",
    "@types/node": "^20.0.0",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    tailwindcss: "^3.4.0",
    postcss: "^8.4.0",
    autoprefixer: "^10.4.0",
  };

  if (has(modules, "auth")) {
    deps["next-auth"] = "^5.0.0";
  }

  if (has(modules, "db")) {
    deps["@prisma/client"] = "^6.0.0";
    devDeps["prisma"] = "^6.0.0";
  }

  if (has(modules, "payments")) {
    deps["stripe"] = "^16.0.0";
  }

  const pkg = {
    name: safeName,
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      ...(has(modules, "db")
        ? { "db:push": "prisma db push", "db:gen": "prisma generate" }
        : {}),
    },
    dependencies: deps,
    devDependencies: devDeps,
  };

  const readme = `# ${blueprint.name || "Generated App"}

${blueprint.description || "Generated by IBlacker App Builder."}

## Modules
- Auth: ${has(modules, "auth") ? "✅" : "❌"}
- Database: ${has(modules, "db") ? "✅" : "❌"}
- Payments: ${has(modules, "payments") ? "✅" : "❌"}

## Features
${(blueprint.features || []).map((f) => `- ${f}`).join("\n") || "- (none)"}

## Pages
${(blueprint.pages || []).map((p) => `- /${p}`).join("\n") || "- (none)"}

## API Endpoints
${(blueprint.apiEndpoints || []).map((p) => `- /api/${p}`).join("\n") || "- (none)"}

## Run
\`\`\`bash
npm install
cp .env.example .env
npm run dev
\`\`\`
`;

  const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root { color-scheme: dark; }
body { background: #000; color: #fff; }
`;

  const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  theme: { extend: {} },
  plugins: [],
};
`;

  const postcssConfig = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;

  const tsconfig = `{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
`;

  const nextEnv = `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
`;

  const layout = `import "./globals.css";

export const metadata = {
  title: "${(blueprint.name || "Generated App").replace(/"/g, '\\"')}",
  description: "${(blueprint.description || "Generated by IBlacker").replace(/"/g, '\\"')}"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div style={{ padding: 24, borderBottom: "1px solid #222", display: "flex", gap: 14, alignItems: "center" }}>
          <a href="/" style={{ fontWeight: 800, textDecoration: "none", color: "white" }}>
            ${blueprint.name || "Generated App"}
          </a>
          <a href="/dashboard" style={{ opacity: 0.8, color: "white" }}>Dashboard</a>
          ${has(modules, "auth") ? `<a href="/signin" style={{ opacity: 0.8, color: "white" }}>Sign in</a>` : ""}
          <span style={{ marginLeft: "auto", opacity: 0.6 }}>by IBlacker</span>
        </div>
        {children}
      </body>
    </html>
  );
}
`;

  const home = pageTemplate(
    blueprint.name || "Generated App",
    blueprint.description || "Generated by IBlacker App Builder."
  );

  const dashboard = `export default function Dashboard() {
  return (
    <main style={{ padding: 40, fontFamily: "system-ui" }}>
      <h1 style={{ fontSize: 28, fontWeight: 800, marginBottom: 16 }}>Dashboard</h1>
      <p style={{ opacity: 0.75, marginBottom: 16 }}>
        ${(blueprint.description || "").replace(/"/g, '\\"')}
      </p>
      <h2 style={{ fontWeight: 700, marginTop: 22 }}>Features</h2>
      <ul style={{ lineHeight: 1.9, opacity: 0.8 }}>
        ${(blueprint.features || []).map((f) => `<li>✅ ${f}</li>`).join("") || `<li>(none)</li>`}
      </ul>
    </main>
  );
}
`;

  /** ===== Base files ===== */
  const files: Record<string, string> = {
    "package.json": JSON.stringify(pkg, null, 2),
    "README.md": readme,
    ".env.example": envExample(modules),
    "next-env.d.ts": nextEnv,
    "tsconfig.json": tsconfig,
    "tailwind.config.js": tailwindConfig,
    "postcss.config.js": postcssConfig,
    "app/globals.css": globalsCss,
    "app/layout.tsx": layout,
    "app/page.tsx": home,
    "app/dashboard/page.tsx": dashboard,
  };

  /** ===== Step 18.6.3 module files ===== */

  // AUTH module
  if (has(modules, "auth")) {
    files["app/api/auth/[...nextauth]/route.ts"] = `import NextAuth from "next-auth";
import Google from "next-auth/providers/google";

const handler = NextAuth({
  providers: [
    Google({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    }),
  ],
});

export { handler as GET, handler as POST };
`;

    files["app/signin/page.tsx"] = `"use client";

import { signIn } from "next-auth/react";

export default function SignIn() {
  return (
    <main style={{ padding: 40, fontFamily: "system-ui" }}>
      <h1 style={{ fontSize: 28, fontWeight: 800, marginBottom: 12 }}>Sign in</h1>
      <button
        onClick={() => signIn("google")}
        style={{
          background: "white",
          color: "black",
          fontWeight: 700,
          padding: "10px 16px",
          borderRadius: 10,
        }}
      >
        Sign in with Google
      </button>
    </main>
  );
}
`;
  }

  // DB module
  if (has(modules, "db")) {
    files["prisma/schema.prisma"] = `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Project {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  prompt    String
  mode      String?
  result    Json?
}
`;

    files["lib/prisma.ts"] = `import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: ["error"],
  });

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
`;
  }

  // PAYMENTS module
  if (has(modules, "payments")) {
    files["lib/stripe.ts"] = `import Stripe from "stripe";

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: "2024-06-20",
});
`;

    files["app/api/checkout/route.ts"] = `import { NextResponse } from "next/server";
import { stripe } from "@/lib/stripe";

export async function POST() {
  const session = await stripe.checkout.sessions.create({
    mode: "payment",
    line_items: [
      {
        price_data: {
          currency: "usd",
          unit_amount: 9900,
          product_data: { name: "IBlacker Pro" },
        },
        quantity: 1,
      },
    ],
    success_url: "http://localhost:3000/dashboard?paid=1",
    cancel_url: "http://localhost:3000/dashboard?paid=0",
  });

  return NextResponse.json({ url: session.url });
}
`;
  }

  /** ===== Generate pages from blueprint.pages ===== */
  const pages = (blueprint.pages || [])
    .map(normalizePagePath)
    .filter(Boolean)
    .filter((p) => p !== "" && p !== "dashboard" && p !== "home" && p !== "/");

  for (const p of pages) {
    const segTitle = p.split("/").slice(-1)[0];
    const title = segTitle.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
    files[`app/${p}/page.tsx`] = pageTemplate(
      title,
      `Generated page for /${p}. Customize this page content.`
    );
  }

  /** ===== Generate API routes from blueprint.apiEndpoints ===== */
  const apis = (blueprint.apiEndpoints || [])
    .map(normalizeApiPath)
    .filter(Boolean);

  for (const ep of apis) {
    files[`app/api/${ep}/route.ts`] = apiTemplate(ep);
  }

  return {
    blueprint,
    files,
  };
}